language: rust

rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libxxf86vm-dev
    - libosmesa6-dev
    - gcc-4.7
    - g++-4.7

before_install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.7 20
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.7 20
  - g++ --version
  - sudo apt-get update -qq
  
notifications:
  webhooks: http://build.servo.org:54856/travis
