language: rust
rust: nightly
sudo: false
addons:
  sources:
    - ubuntu-toolchain-r-test
  apt:
    packages:
    - libxxf86vm-dev
    - libosmesa6-dev
    - gcc-4.7
    - g++-4.7
  
notifications:
  webhooks: http://build.servo.org:54856/travis
