[package]
name = "azure"
version = "0.4.5"
authors = ["The Servo Project Developers"]
documentation = "http://doc.servo.org/azure/"

build = "build.rs"

[features]
default = []
plugins = ["serde", "serde_macros", "heapsize", "heapsize_plugin", "euclid/plugins"]


[dependencies]
euclid = "0.7.0"
heapsize = {version = ">=0.2, <0.4", optional = true}
heapsize_plugin = {version = "0.1.0", optional = true}
libc = "0.2"
serde = {version = ">=0.6.1, <0.8", optional = true}
serde_macros = {version = ">=0.6.1, <0.8", optional = true}
servo-skia = "0.20130412.10"

[target.'cfg(not(target_os = "macos"))'.dependencies]
freetype = { git = "https://github.com/servo/rust-freetype" }
servo-freetype-sys = "2.4.11"

[target.'cfg(target_os = "linux")'.dependencies]
x11 = { version = "2.0.0", features = ["xlib"] }

[target.'cfg(target_os = "android")'.dependencies]
servo-egl = "0.2"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.2.0"
core-graphics = ">=0.2.0, <0.4"
core-text = "1.0"
