[package]
name = "azure"
version = "0.21.2"
authors = ["The Servo Project Developers"]
documentation = "http://doc.servo.org/azure/"
repository = "https://github.com/servo/rust-azure"
description = "Bindings to Mozilla's Moz2D library"
license = "MPL-2.0"

build = "build.rs"

[features]
default = []
plugins = ["serde", "serde_derive", "heapsize", "heapsize_derive"]

[build-dependencies]
cmake = "0.1"

[dependencies]
euclid = "0.15"
heapsize = {version = "0.4", optional = true}
heapsize_derive = {version = "0.1.0", optional = true}
libc = "0.2"
serde = {version = "1.0", optional = true}
serde_derive = {version = "1.0", optional = true}
servo-skia = "0.30000006"

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies]
servo-freetype-sys = "4.0.1"
